package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurrentQuarterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentQuarterAllPropertiesEquals(CurrentQuarter expected, CurrentQuarter actual) {
        assertCurrentQuarterAutoGeneratedPropertiesEquals(expected, actual);
        assertCurrentQuarterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentQuarterAllUpdatablePropertiesEquals(CurrentQuarter expected, CurrentQuarter actual) {
        assertCurrentQuarterUpdatableFieldsEquals(expected, actual);
        assertCurrentQuarterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentQuarterAutoGeneratedPropertiesEquals(CurrentQuarter expected, CurrentQuarter actual) {
        assertThat(actual)
            .as("Verify CurrentQuarter auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentQuarterUpdatableFieldsEquals(CurrentQuarter expected, CurrentQuarter actual) {
        assertThat(actual)
            .as("Verify CurrentQuarter relevant properties")
            .satisfies(a -> assertThat(a.getScheduledQuarter()).as("check scheduledQuarter").isEqualTo(expected.getScheduledQuarter()))
            .satisfies(a -> assertThat(a.getStartQuarter()).as("check startQuarter").isEqualTo(expected.getStartQuarter()))
            .satisfies(a -> assertThat(a.getEndQuarter()).as("check endQuarter").isEqualTo(expected.getEndQuarter()))
            .satisfies(a ->
                assertThat(a.getCurrentQuarterState()).as("check currentQuarterState").isEqualTo(expected.getCurrentQuarterState())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentQuarterUpdatableRelationshipsEquals(CurrentQuarter expected, CurrentQuarter actual) {
        assertThat(actual)
            .as("Verify CurrentQuarter relationships")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()));
    }
}
