package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class GeneralObservationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneralObservationAllPropertiesEquals(GeneralObservation expected, GeneralObservation actual) {
        assertGeneralObservationAutoGeneratedPropertiesEquals(expected, actual);
        assertGeneralObservationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneralObservationAllUpdatablePropertiesEquals(GeneralObservation expected, GeneralObservation actual) {
        assertGeneralObservationUpdatableFieldsEquals(expected, actual);
        assertGeneralObservationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneralObservationAutoGeneratedPropertiesEquals(GeneralObservation expected, GeneralObservation actual) {
        assertThat(actual)
            .as("Verify GeneralObservation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneralObservationUpdatableFieldsEquals(GeneralObservation expected, GeneralObservation actual) {
        assertThat(actual)
            .as("Verify GeneralObservation relevant properties")
            .satisfies(a -> assertThat(a.getNumber()).as("check number").isEqualTo(expected.getNumber()))
            .satisfies(a ->
                assertThat(a.getObservationGeneral()).as("check observationGeneral").isEqualTo(expected.getObservationGeneral())
            )
            .satisfies(a -> assertThat(a.getJury()).as("check jury").isEqualTo(expected.getJury()))
            .satisfies(a ->
                assertThat(a.getDateAudit())
                    .as("check dateAudit")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateAudit())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneralObservationUpdatableRelationshipsEquals(GeneralObservation expected, GeneralObservation actual) {
        assertThat(actual)
            .as("Verify GeneralObservation relationships")
            .satisfies(a -> assertThat(a.getProjectGroup()).as("check projectGroup").isEqualTo(expected.getProjectGroup()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
