package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LearningCompetenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetenceAllPropertiesEquals(LearningCompetence expected, LearningCompetence actual) {
        assertLearningCompetenceAutoGeneratedPropertiesEquals(expected, actual);
        assertLearningCompetenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetenceAllUpdatablePropertiesEquals(LearningCompetence expected, LearningCompetence actual) {
        assertLearningCompetenceUpdatableFieldsEquals(expected, actual);
        assertLearningCompetenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetenceAutoGeneratedPropertiesEquals(LearningCompetence expected, LearningCompetence actual) {
        assertThat(actual)
            .as("Verify LearningCompetence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetenceUpdatableFieldsEquals(LearningCompetence expected, LearningCompetence actual) {
        assertThat(actual)
            .as("Verify LearningCompetence relevant properties")
            .satisfies(a -> assertThat(a.getCompetenceCode()).as("check competenceCode").isEqualTo(expected.getCompetenceCode()))
            .satisfies(a ->
                assertThat(a.getCompetitionDenomination())
                    .as("check competitionDenomination")
                    .isEqualTo(expected.getCompetitionDenomination())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetenceUpdatableRelationshipsEquals(LearningCompetence expected, LearningCompetence actual) {
        assertThat(actual)
            .as("Verify LearningCompetence relationships")
            .satisfies(a -> assertThat(a.getTrainingProgram()).as("check trainingProgram").isEqualTo(expected.getTrainingProgram()));
    }
}
