package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectPhaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectPhaseAllPropertiesEquals(ProjectPhase expected, ProjectPhase actual) {
        assertProjectPhaseAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectPhaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectPhaseAllUpdatablePropertiesEquals(ProjectPhase expected, ProjectPhase actual) {
        assertProjectPhaseUpdatableFieldsEquals(expected, actual);
        assertProjectPhaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectPhaseAutoGeneratedPropertiesEquals(ProjectPhase expected, ProjectPhase actual) {
        assertThat(actual)
            .as("Verify ProjectPhase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectPhaseUpdatableFieldsEquals(ProjectPhase expected, ProjectPhase actual) {
        assertThat(actual)
            .as("Verify ProjectPhase relevant properties")
            .satisfies(a -> assertThat(a.getProjectPhaseCode()).as("check projectPhaseCode").isEqualTo(expected.getProjectPhaseCode()))
            .satisfies(a -> assertThat(a.getProjectPhaseState()).as("check projectPhaseState").isEqualTo(expected.getProjectPhaseState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectPhaseUpdatableRelationshipsEquals(ProjectPhase expected, ProjectPhase actual) {
        assertThat(actual)
            .as("Verify ProjectPhase relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
