package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingProgramAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingProgramAllPropertiesEquals(TrainingProgram expected, TrainingProgram actual) {
        assertTrainingProgramAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingProgramAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingProgramAllUpdatablePropertiesEquals(TrainingProgram expected, TrainingProgram actual) {
        assertTrainingProgramUpdatableFieldsEquals(expected, actual);
        assertTrainingProgramUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingProgramAutoGeneratedPropertiesEquals(TrainingProgram expected, TrainingProgram actual) {
        assertThat(actual)
            .as("Verify TrainingProgram auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingProgramUpdatableFieldsEquals(TrainingProgram expected, TrainingProgram actual) {
        assertThat(actual)
            .as("Verify TrainingProgram relevant properties")
            .satisfies(a -> assertThat(a.getProgramCode()).as("check programCode").isEqualTo(expected.getProgramCode()))
            .satisfies(a -> assertThat(a.getProgramVersion()).as("check programVersion").isEqualTo(expected.getProgramVersion()))
            .satisfies(a -> assertThat(a.getProgramName()).as("check programName").isEqualTo(expected.getProgramName()))
            .satisfies(a -> assertThat(a.getProgramInitials()).as("check programInitials").isEqualTo(expected.getProgramInitials()))
            .satisfies(a -> assertThat(a.getProgramState()).as("check programState").isEqualTo(expected.getProgramState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingProgramUpdatableRelationshipsEquals(TrainingProgram expected, TrainingProgram actual) {
        assertThat(actual)
            .as("Verify TrainingProgram relationships")
            .satisfies(a -> assertThat(a.getLevelEducation()).as("check levelEducation").isEqualTo(expected.getLevelEducation()));
    }
}
