package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkingDayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayAllPropertiesEquals(WorkingDay expected, WorkingDay actual) {
        assertWorkingDayAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkingDayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayAllUpdatablePropertiesEquals(WorkingDay expected, WorkingDay actual) {
        assertWorkingDayUpdatableFieldsEquals(expected, actual);
        assertWorkingDayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayAutoGeneratedPropertiesEquals(WorkingDay expected, WorkingDay actual) {
        assertThat(actual)
            .as("Verify WorkingDay auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayUpdatableFieldsEquals(WorkingDay expected, WorkingDay actual) {
        assertThat(actual)
            .as("Verify WorkingDay relevant properties")
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayUpdatableRelationshipsEquals(WorkingDay expected, WorkingDay actual) {
        assertThat(actual)
            .as("Verify WorkingDay relationships")
            .satisfies(a ->
                assertThat(a.getInstructorWorkingDay()).as("check instructorWorkingDay").isEqualTo(expected.getInstructorWorkingDay())
            )
            .satisfies(a -> assertThat(a.getDay()).as("check day").isEqualTo(expected.getDay()));
    }
}
