package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BondingInstructorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingInstructorAllPropertiesEquals(BondingInstructor expected, BondingInstructor actual) {
        assertBondingInstructorAutoGeneratedPropertiesEquals(expected, actual);
        assertBondingInstructorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingInstructorAllUpdatablePropertiesEquals(BondingInstructor expected, BondingInstructor actual) {
        assertBondingInstructorUpdatableFieldsEquals(expected, actual);
        assertBondingInstructorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingInstructorAutoGeneratedPropertiesEquals(BondingInstructor expected, BondingInstructor actual) {
        assertThat(actual)
            .as("Verify BondingInstructor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingInstructorUpdatableFieldsEquals(BondingInstructor expected, BondingInstructor actual) {
        assertThat(actual)
            .as("Verify BondingInstructor relevant properties")
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingInstructorUpdatableRelationshipsEquals(BondingInstructor expected, BondingInstructor actual) {
        assertThat(actual)
            .as("Verify BondingInstructor relationships")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getInstructor()).as("check instructor").isEqualTo(expected.getInstructor()))
            .satisfies(a -> assertThat(a.getBonding()).as("check bonding").isEqualTo(expected.getBonding()));
    }
}
