package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BondingCompetenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingCompetenceAllPropertiesEquals(BondingCompetence expected, BondingCompetence actual) {
        assertBondingCompetenceAutoGeneratedPropertiesEquals(expected, actual);
        assertBondingCompetenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingCompetenceAllUpdatablePropertiesEquals(BondingCompetence expected, BondingCompetence actual) {
        assertBondingCompetenceUpdatableFieldsEquals(expected, actual);
        assertBondingCompetenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingCompetenceAutoGeneratedPropertiesEquals(BondingCompetence expected, BondingCompetence actual) {
        assertThat(actual)
            .as("Verify BondingCompetence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingCompetenceUpdatableFieldsEquals(BondingCompetence expected, BondingCompetence actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingCompetenceUpdatableRelationshipsEquals(BondingCompetence expected, BondingCompetence actual) {
        assertThat(actual)
            .as("Verify BondingCompetence relationships")
            .satisfies(a -> assertThat(a.getBondingInstructor()).as("check bondingInstructor").isEqualTo(expected.getBondingInstructor()))
            .satisfies(a ->
                assertThat(a.getLearningCompetence()).as("check learningCompetence").isEqualTo(expected.getLearningCompetence())
            );
    }
}
