package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayAllPropertiesEquals(Day expected, Day actual) {
        assertDayAutoGeneratedPropertiesEquals(expected, actual);
        assertDayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayAllUpdatablePropertiesEquals(Day expected, Day actual) {
        assertDayUpdatableFieldsEquals(expected, actual);
        assertDayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayAutoGeneratedPropertiesEquals(Day expected, Day actual) {
        assertThat(actual)
            .as("Verify Day auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUpdatableFieldsEquals(Day expected, Day actual) {
        assertThat(actual)
            .as("Verify Day relevant properties")
            .satisfies(a -> assertThat(a.getDayName()).as("check dayName").isEqualTo(expected.getDayName()))
            .satisfies(a -> assertThat(a.getDayState()).as("check dayState").isEqualTo(expected.getDayState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUpdatableRelationshipsEquals(Day expected, Day actual) {
        // empty method
    }
}
