package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class GroupResponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupResponseAllPropertiesEquals(GroupResponse expected, GroupResponse actual) {
        assertGroupResponseAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupResponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupResponseAllUpdatablePropertiesEquals(GroupResponse expected, GroupResponse actual) {
        assertGroupResponseUpdatableFieldsEquals(expected, actual);
        assertGroupResponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupResponseAutoGeneratedPropertiesEquals(GroupResponse expected, GroupResponse actual) {
        assertThat(actual)
            .as("Verify GroupResponse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupResponseUpdatableFieldsEquals(GroupResponse expected, GroupResponse actual) {
        assertThat(actual)
            .as("Verify GroupResponse relevant properties")
            .satisfies(a ->
                assertThat(a.getEvaluationDate())
                    .as("check evaluationDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getEvaluationDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupResponseUpdatableRelationshipsEquals(GroupResponse expected, GroupResponse actual) {
        assertThat(actual)
            .as("Verify GroupResponse relationships")
            .satisfies(a -> assertThat(a.getProjectGroup()).as("check projectGroup").isEqualTo(expected.getProjectGroup()))
            .satisfies(a -> assertThat(a.getAssessment()).as("check assessment").isEqualTo(expected.getAssessment()))
            .satisfies(a -> assertThat(a.getItemList()).as("check itemList").isEqualTo(expected.getItemList()));
    }
}
