package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrimesterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrimesterAllPropertiesEquals(Trimester expected, Trimester actual) {
        assertTrimesterAutoGeneratedPropertiesEquals(expected, actual);
        assertTrimesterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrimesterAllUpdatablePropertiesEquals(Trimester expected, Trimester actual) {
        assertTrimesterUpdatableFieldsEquals(expected, actual);
        assertTrimesterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrimesterAutoGeneratedPropertiesEquals(Trimester expected, Trimester actual) {
        assertThat(actual)
            .as("Verify Trimester auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrimesterUpdatableFieldsEquals(Trimester expected, Trimester actual) {
        assertThat(actual)
            .as("Verify Trimester relevant properties")
            .satisfies(a -> assertThat(a.getTrimesterName()).as("check trimesterName").isEqualTo(expected.getTrimesterName()))
            .satisfies(a -> assertThat(a.getTrimesterState()).as("check trimesterState").isEqualTo(expected.getTrimesterState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrimesterUpdatableRelationshipsEquals(Trimester expected, Trimester actual) {
        assertThat(actual)
            .as("Verify Trimester relationships")
            .satisfies(a -> assertThat(a.getWorkingDayCourse()).as("check workingDayCourse").isEqualTo(expected.getWorkingDayCourse()))
            .satisfies(a -> assertThat(a.getLevelEducations()).as("check levelEducations").isEqualTo(expected.getLevelEducations()));
    }
}
