package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkingDayCourseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayCourseAllPropertiesEquals(WorkingDayCourse expected, WorkingDayCourse actual) {
        assertWorkingDayCourseAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkingDayCourseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayCourseAllUpdatablePropertiesEquals(WorkingDayCourse expected, WorkingDayCourse actual) {
        assertWorkingDayCourseUpdatableFieldsEquals(expected, actual);
        assertWorkingDayCourseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayCourseAutoGeneratedPropertiesEquals(WorkingDayCourse expected, WorkingDayCourse actual) {
        assertThat(actual)
            .as("Verify WorkingDayCourse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayCourseUpdatableFieldsEquals(WorkingDayCourse expected, WorkingDayCourse actual) {
        assertThat(actual)
            .as("Verify WorkingDayCourse relevant properties")
            .satisfies(a -> assertThat(a.getWorkingDayAcronym()).as("check workingDayAcronym").isEqualTo(expected.getWorkingDayAcronym()))
            .satisfies(a -> assertThat(a.getWorkingDayName()).as("check workingDayName").isEqualTo(expected.getWorkingDayName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getStateWorkingDay()).as("check stateWorkingDay").isEqualTo(expected.getStateWorkingDay()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingDayCourseUpdatableRelationshipsEquals(WorkingDayCourse expected, WorkingDayCourse actual) {
        // empty method
    }
}
