package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AreaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaAllPropertiesEquals(Area expected, Area actual) {
        assertAreaAutoGeneratedPropertiesEquals(expected, actual);
        assertAreaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaAllUpdatablePropertiesEquals(Area expected, Area actual) {
        assertAreaUpdatableFieldsEquals(expected, actual);
        assertAreaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaAutoGeneratedPropertiesEquals(Area expected, Area actual) {
        assertThat(actual)
            .as("Verify Area auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaUpdatableFieldsEquals(Area expected, Area actual) {
        assertThat(actual)
            .as("Verify Area relevant properties")
            .satisfies(a -> assertThat(a.getAreaName()).as("check areaName").isEqualTo(expected.getAreaName()))
            .satisfies(a -> assertThat(a.getUrlLogo()).as("check urlLogo").isEqualTo(expected.getUrlLogo()))
            .satisfies(a -> assertThat(a.getAreaState()).as("check areaState").isEqualTo(expected.getAreaState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaUpdatableRelationshipsEquals(Area expected, Area actual) {
        // empty method
    }
}
