package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassroomLimitationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomLimitationAllPropertiesEquals(ClassroomLimitation expected, ClassroomLimitation actual) {
        assertClassroomLimitationAutoGeneratedPropertiesEquals(expected, actual);
        assertClassroomLimitationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomLimitationAllUpdatablePropertiesEquals(ClassroomLimitation expected, ClassroomLimitation actual) {
        assertClassroomLimitationUpdatableFieldsEquals(expected, actual);
        assertClassroomLimitationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomLimitationAutoGeneratedPropertiesEquals(ClassroomLimitation expected, ClassroomLimitation actual) {
        assertThat(actual)
            .as("Verify ClassroomLimitation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomLimitationUpdatableFieldsEquals(ClassroomLimitation expected, ClassroomLimitation actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomLimitationUpdatableRelationshipsEquals(ClassroomLimitation expected, ClassroomLimitation actual) {
        assertThat(actual)
            .as("Verify ClassroomLimitation relationships")
            .satisfies(a -> assertThat(a.getClassroom()).as("check classroom").isEqualTo(expected.getClassroom()))
            .satisfies(a -> assertThat(a.getLearningResult()).as("check learningResult").isEqualTo(expected.getLearningResult()));
    }
}
