package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ItemListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemListAllPropertiesEquals(ItemList expected, ItemList actual) {
        assertItemListAutoGeneratedPropertiesEquals(expected, actual);
        assertItemListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemListAllUpdatablePropertiesEquals(ItemList expected, ItemList actual) {
        assertItemListUpdatableFieldsEquals(expected, actual);
        assertItemListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemListAutoGeneratedPropertiesEquals(ItemList expected, ItemList actual) {
        assertThat(actual)
            .as("Verify ItemList auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemListUpdatableFieldsEquals(ItemList expected, ItemList actual) {
        assertThat(actual)
            .as("Verify ItemList relevant properties")
            .satisfies(a -> assertThat(a.getItemNumber()).as("check itemNumber").isEqualTo(expected.getItemNumber()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemListUpdatableRelationshipsEquals(ItemList expected, ItemList actual) {
        assertThat(actual)
            .as("Verify ItemList relationships")
            .satisfies(a -> assertThat(a.getCheckList()).as("check checkList").isEqualTo(expected.getCheckList()))
            .satisfies(a -> assertThat(a.getLearningResult()).as("check learningResult").isEqualTo(expected.getLearningResult()));
    }
}
