package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LearningResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningResultAllPropertiesEquals(LearningResult expected, LearningResult actual) {
        assertLearningResultAutoGeneratedPropertiesEquals(expected, actual);
        assertLearningResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningResultAllUpdatablePropertiesEquals(LearningResult expected, LearningResult actual) {
        assertLearningResultUpdatableFieldsEquals(expected, actual);
        assertLearningResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningResultAutoGeneratedPropertiesEquals(LearningResult expected, LearningResult actual) {
        assertThat(actual)
            .as("Verify LearningResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningResultUpdatableFieldsEquals(LearningResult expected, LearningResult actual) {
        assertThat(actual)
            .as("Verify LearningResult relevant properties")
            .satisfies(a -> assertThat(a.getResultCode()).as("check resultCode").isEqualTo(expected.getResultCode()))
            .satisfies(a -> assertThat(a.getDenomination()).as("check denomination").isEqualTo(expected.getDenomination()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningResultUpdatableRelationshipsEquals(LearningResult expected, LearningResult actual) {
        assertThat(actual)
            .as("Verify LearningResult relationships")
            .satisfies(a ->
                assertThat(a.getLearningCompetence()).as("check learningCompetence").isEqualTo(expected.getLearningCompetence())
            );
    }
}
