package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuarterScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuarterScheduleAllPropertiesEquals(QuarterSchedule expected, QuarterSchedule actual) {
        assertQuarterScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertQuarterScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuarterScheduleAllUpdatablePropertiesEquals(QuarterSchedule expected, QuarterSchedule actual) {
        assertQuarterScheduleUpdatableFieldsEquals(expected, actual);
        assertQuarterScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuarterScheduleAutoGeneratedPropertiesEquals(QuarterSchedule expected, QuarterSchedule actual) {
        assertThat(actual)
            .as("Verify QuarterSchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuarterScheduleUpdatableFieldsEquals(QuarterSchedule expected, QuarterSchedule actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuarterScheduleUpdatableRelationshipsEquals(QuarterSchedule expected, QuarterSchedule actual) {
        assertThat(actual)
            .as("Verify QuarterSchedule relationships")
            .satisfies(a -> assertThat(a.getLearningResult()).as("check learningResult").isEqualTo(expected.getLearningResult()))
            .satisfies(a -> assertThat(a.getPlanning()).as("check planning").isEqualTo(expected.getPlanning()))
            .satisfies(a -> assertThat(a.getTrimester()).as("check trimester").isEqualTo(expected.getTrimester()));
    }
}
