package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ViewedResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewedResultAllPropertiesEquals(ViewedResult expected, ViewedResult actual) {
        assertViewedResultAutoGeneratedPropertiesEquals(expected, actual);
        assertViewedResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewedResultAllUpdatablePropertiesEquals(ViewedResult expected, ViewedResult actual) {
        assertViewedResultUpdatableFieldsEquals(expected, actual);
        assertViewedResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewedResultAutoGeneratedPropertiesEquals(ViewedResult expected, ViewedResult actual) {
        assertThat(actual)
            .as("Verify ViewedResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewedResultUpdatableFieldsEquals(ViewedResult expected, ViewedResult actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertViewedResultUpdatableRelationshipsEquals(ViewedResult expected, ViewedResult actual) {
        assertThat(actual)
            .as("Verify ViewedResult relationships")
            .satisfies(a -> assertThat(a.getCourseTrimester()).as("check courseTrimester").isEqualTo(expected.getCourseTrimester()))
            .satisfies(a -> assertThat(a.getPlanning()).as("check planning").isEqualTo(expected.getPlanning()))
            .satisfies(a -> assertThat(a.getLearningResult()).as("check learningResult").isEqualTo(expected.getLearningResult()));
    }
}
