package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AreaInstructorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaInstructorAllPropertiesEquals(AreaInstructor expected, AreaInstructor actual) {
        assertAreaInstructorAutoGeneratedPropertiesEquals(expected, actual);
        assertAreaInstructorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaInstructorAllUpdatablePropertiesEquals(AreaInstructor expected, AreaInstructor actual) {
        assertAreaInstructorUpdatableFieldsEquals(expected, actual);
        assertAreaInstructorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaInstructorAutoGeneratedPropertiesEquals(AreaInstructor expected, AreaInstructor actual) {
        assertThat(actual)
            .as("Verify AreaInstructor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaInstructorUpdatableFieldsEquals(AreaInstructor expected, AreaInstructor actual) {
        assertThat(actual)
            .as("Verify AreaInstructor relevant properties")
            .satisfies(a ->
                assertThat(a.getAreaInstructorState()).as("check areaInstructorState").isEqualTo(expected.getAreaInstructorState())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaInstructorUpdatableRelationshipsEquals(AreaInstructor expected, AreaInstructor actual) {
        assertThat(actual)
            .as("Verify AreaInstructor relationships")
            .satisfies(a -> assertThat(a.getArea()).as("check area").isEqualTo(expected.getArea()))
            .satisfies(a -> assertThat(a.getInstructor()).as("check instructor").isEqualTo(expected.getInstructor()));
    }
}
