package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssessmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAllPropertiesEquals(Assessment expected, Assessment actual) {
        assertAssessmentAutoGeneratedPropertiesEquals(expected, actual);
        assertAssessmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAllUpdatablePropertiesEquals(Assessment expected, Assessment actual) {
        assertAssessmentUpdatableFieldsEquals(expected, actual);
        assertAssessmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAutoGeneratedPropertiesEquals(Assessment expected, Assessment actual) {
        assertThat(actual)
            .as("Verify Assessment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentUpdatableFieldsEquals(Assessment expected, Assessment actual) {
        assertThat(actual)
            .as("Verify Assessment relevant properties")
            .satisfies(a -> assertThat(a.getAssessmentType()).as("check assessmentType").isEqualTo(expected.getAssessmentType()))
            .satisfies(a -> assertThat(a.getAssessmentState()).as("check assessmentState").isEqualTo(expected.getAssessmentState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentUpdatableRelationshipsEquals(Assessment expected, Assessment actual) {
        // empty method
    }
}
