package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BondingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingAllPropertiesEquals(Bonding expected, Bonding actual) {
        assertBondingAutoGeneratedPropertiesEquals(expected, actual);
        assertBondingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingAllUpdatablePropertiesEquals(Bonding expected, Bonding actual) {
        assertBondingUpdatableFieldsEquals(expected, actual);
        assertBondingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingAutoGeneratedPropertiesEquals(Bonding expected, Bonding actual) {
        assertThat(actual)
            .as("Verify Bonding auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingUpdatableFieldsEquals(Bonding expected, Bonding actual) {
        assertThat(actual)
            .as("Verify Bonding relevant properties")
            .satisfies(a -> assertThat(a.getBondingType()).as("check bondingType").isEqualTo(expected.getBondingType()))
            .satisfies(a -> assertThat(a.getWorkingHours()).as("check workingHours").isEqualTo(expected.getWorkingHours()))
            .satisfies(a -> assertThat(a.getBondingState()).as("check bondingState").isEqualTo(expected.getBondingState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBondingUpdatableRelationshipsEquals(Bonding expected, Bonding actual) {
        // empty method
    }
}
