package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoundingScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoundingScheduleAllPropertiesEquals(BoundingSchedule expected, BoundingSchedule actual) {
        assertBoundingScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertBoundingScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoundingScheduleAllUpdatablePropertiesEquals(BoundingSchedule expected, BoundingSchedule actual) {
        assertBoundingScheduleUpdatableFieldsEquals(expected, actual);
        assertBoundingScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoundingScheduleAutoGeneratedPropertiesEquals(BoundingSchedule expected, BoundingSchedule actual) {
        assertThat(actual)
            .as("Verify BoundingSchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoundingScheduleUpdatableFieldsEquals(BoundingSchedule expected, BoundingSchedule actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoundingScheduleUpdatableRelationshipsEquals(BoundingSchedule expected, BoundingSchedule actual) {
        assertThat(actual)
            .as("Verify BoundingSchedule relationships")
            .satisfies(a -> assertThat(a.getBondingInstructor()).as("check bondingInstructor").isEqualTo(expected.getBondingInstructor()))
            .satisfies(a ->
                assertThat(a.getInstructorWorkingDay()).as("check instructorWorkingDay").isEqualTo(expected.getInstructorWorkingDay())
            );
    }
}
