package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CampusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampusAllPropertiesEquals(Campus expected, Campus actual) {
        assertCampusAutoGeneratedPropertiesEquals(expected, actual);
        assertCampusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampusAllUpdatablePropertiesEquals(Campus expected, Campus actual) {
        assertCampusUpdatableFieldsEquals(expected, actual);
        assertCampusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampusAutoGeneratedPropertiesEquals(Campus expected, Campus actual) {
        assertThat(actual)
            .as("Verify Campus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampusUpdatableFieldsEquals(Campus expected, Campus actual) {
        assertThat(actual)
            .as("Verify Campus relevant properties")
            .satisfies(a -> assertThat(a.getCampusName()).as("check campusName").isEqualTo(expected.getCampusName()))
            .satisfies(a -> assertThat(a.getCampusAddress()).as("check campusAddress").isEqualTo(expected.getCampusAddress()))
            .satisfies(a -> assertThat(a.getCampusState()).as("check campusState").isEqualTo(expected.getCampusState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampusUpdatableRelationshipsEquals(Campus expected, Campus actual) {
        // empty method
    }
}
