package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckListCourseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListCourseAllPropertiesEquals(CheckListCourse expected, CheckListCourse actual) {
        assertCheckListCourseAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckListCourseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListCourseAllUpdatablePropertiesEquals(CheckListCourse expected, CheckListCourse actual) {
        assertCheckListCourseUpdatableFieldsEquals(expected, actual);
        assertCheckListCourseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListCourseAutoGeneratedPropertiesEquals(CheckListCourse expected, CheckListCourse actual) {
        assertThat(actual)
            .as("Verify CheckListCourse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListCourseUpdatableFieldsEquals(CheckListCourse expected, CheckListCourse actual) {
        assertThat(actual)
            .as("Verify CheckListCourse relevant properties")
            .satisfies(a -> assertThat(a.getCheckListState()).as("check checkListState").isEqualTo(expected.getCheckListState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListCourseUpdatableRelationshipsEquals(CheckListCourse expected, CheckListCourse actual) {
        assertThat(actual)
            .as("Verify CheckListCourse relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getCheckList()).as("check checkList").isEqualTo(expected.getCheckList()));
    }
}
