package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassroomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomAllPropertiesEquals(Classroom expected, Classroom actual) {
        assertClassroomAutoGeneratedPropertiesEquals(expected, actual);
        assertClassroomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomAllUpdatablePropertiesEquals(Classroom expected, Classroom actual) {
        assertClassroomUpdatableFieldsEquals(expected, actual);
        assertClassroomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomAutoGeneratedPropertiesEquals(Classroom expected, Classroom actual) {
        assertThat(actual)
            .as("Verify Classroom auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomUpdatableFieldsEquals(Classroom expected, Classroom actual) {
        assertThat(actual)
            .as("Verify Classroom relevant properties")
            .satisfies(a -> assertThat(a.getClassroomNumber()).as("check classroomNumber").isEqualTo(expected.getClassroomNumber()))
            .satisfies(a ->
                assertThat(a.getClassroomDescription()).as("check classroomDescription").isEqualTo(expected.getClassroomDescription())
            )
            .satisfies(a -> assertThat(a.getClassroomState()).as("check classroomState").isEqualTo(expected.getClassroomState()))
            .satisfies(a -> assertThat(a.getLimitation()).as("check limitation").isEqualTo(expected.getLimitation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomUpdatableRelationshipsEquals(Classroom expected, Classroom actual) {
        assertThat(actual)
            .as("Verify Classroom relationships")
            .satisfies(a -> assertThat(a.getClassroomType()).as("check classroomType").isEqualTo(expected.getClassroomType()))
            .satisfies(a -> assertThat(a.getCampus()).as("check campus").isEqualTo(expected.getCampus()));
    }
}
