package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassroomTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomTypeAllPropertiesEquals(ClassroomType expected, ClassroomType actual) {
        assertClassroomTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertClassroomTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomTypeAllUpdatablePropertiesEquals(ClassroomType expected, ClassroomType actual) {
        assertClassroomTypeUpdatableFieldsEquals(expected, actual);
        assertClassroomTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomTypeAutoGeneratedPropertiesEquals(ClassroomType expected, ClassroomType actual) {
        assertThat(actual)
            .as("Verify ClassroomType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomTypeUpdatableFieldsEquals(ClassroomType expected, ClassroomType actual) {
        assertThat(actual)
            .as("Verify ClassroomType relevant properties")
            .satisfies(a -> assertThat(a.getTypeClassroom()).as("check typeClassroom").isEqualTo(expected.getTypeClassroom()))
            .satisfies(a ->
                assertThat(a.getClassroomDescription()).as("check classroomDescription").isEqualTo(expected.getClassroomDescription())
            )
            .satisfies(a -> assertThat(a.getClassroomState()).as("check classroomState").isEqualTo(expected.getClassroomState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassroomTypeUpdatableRelationshipsEquals(ClassroomType expected, ClassroomType actual) {
        // empty method
    }
}
