package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseTrimesterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseTrimesterAllPropertiesEquals(CourseTrimester expected, CourseTrimester actual) {
        assertCourseTrimesterAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseTrimesterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseTrimesterAllUpdatablePropertiesEquals(CourseTrimester expected, CourseTrimester actual) {
        assertCourseTrimesterUpdatableFieldsEquals(expected, actual);
        assertCourseTrimesterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseTrimesterAutoGeneratedPropertiesEquals(CourseTrimester expected, CourseTrimester actual) {
        assertThat(actual)
            .as("Verify CourseTrimester auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseTrimesterUpdatableFieldsEquals(CourseTrimester expected, CourseTrimester actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseTrimesterUpdatableRelationshipsEquals(CourseTrimester expected, CourseTrimester actual) {
        assertThat(actual)
            .as("Verify CourseTrimester relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getTrimester()).as("check trimester").isEqualTo(expected.getTrimester()));
    }
}
