package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseStatusAllPropertiesEquals(CourseStatus expected, CourseStatus actual) {
        assertCourseStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseStatusAllUpdatablePropertiesEquals(CourseStatus expected, CourseStatus actual) {
        assertCourseStatusUpdatableFieldsEquals(expected, actual);
        assertCourseStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseStatusAutoGeneratedPropertiesEquals(CourseStatus expected, CourseStatus actual) {
        assertThat(actual)
            .as("Verify CourseStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseStatusUpdatableFieldsEquals(CourseStatus expected, CourseStatus actual) {
        assertThat(actual)
            .as("Verify CourseStatus relevant properties")
            .satisfies(a -> assertThat(a.getNameCourseStatus()).as("check nameCourseStatus").isEqualTo(expected.getNameCourseStatus()))
            .satisfies(a -> assertThat(a.getStateCourse()).as("check stateCourse").isEqualTo(expected.getStateCourse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseStatusUpdatableRelationshipsEquals(CourseStatus expected, CourseStatus actual) {
        // empty method
    }
}
