package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoursePlanningAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePlanningAllPropertiesEquals(CoursePlanning expected, CoursePlanning actual) {
        assertCoursePlanningAutoGeneratedPropertiesEquals(expected, actual);
        assertCoursePlanningAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePlanningAllUpdatablePropertiesEquals(CoursePlanning expected, CoursePlanning actual) {
        assertCoursePlanningUpdatableFieldsEquals(expected, actual);
        assertCoursePlanningUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePlanningAutoGeneratedPropertiesEquals(CoursePlanning expected, CoursePlanning actual) {
        assertThat(actual)
            .as("Verify CoursePlanning auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePlanningUpdatableFieldsEquals(CoursePlanning expected, CoursePlanning actual) {
        assertThat(actual)
            .as("Verify CoursePlanning relevant properties")
            .satisfies(a ->
                assertThat(a.getStateCoursePlanning()).as("check stateCoursePlanning").isEqualTo(expected.getStateCoursePlanning())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePlanningUpdatableRelationshipsEquals(CoursePlanning expected, CoursePlanning actual) {
        assertThat(actual)
            .as("Verify CoursePlanning relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getPlanning()).as("check planning").isEqualTo(expected.getPlanning()));
    }
}
