package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstructorWorkingDayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorWorkingDayAllPropertiesEquals(InstructorWorkingDay expected, InstructorWorkingDay actual) {
        assertInstructorWorkingDayAutoGeneratedPropertiesEquals(expected, actual);
        assertInstructorWorkingDayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorWorkingDayAllUpdatablePropertiesEquals(InstructorWorkingDay expected, InstructorWorkingDay actual) {
        assertInstructorWorkingDayUpdatableFieldsEquals(expected, actual);
        assertInstructorWorkingDayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorWorkingDayAutoGeneratedPropertiesEquals(InstructorWorkingDay expected, InstructorWorkingDay actual) {
        assertThat(actual)
            .as("Verify InstructorWorkingDay auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorWorkingDayUpdatableFieldsEquals(InstructorWorkingDay expected, InstructorWorkingDay actual) {
        assertThat(actual)
            .as("Verify InstructorWorkingDay relevant properties")
            .satisfies(a -> assertThat(a.getNameWorkingDay()).as("check nameWorkingDay").isEqualTo(expected.getNameWorkingDay()))
            .satisfies(a ->
                assertThat(a.getDescriptionWorkingDay()).as("check descriptionWorkingDay").isEqualTo(expected.getDescriptionWorkingDay())
            )
            .satisfies(a -> assertThat(a.getWorkingDayState()).as("check workingDayState").isEqualTo(expected.getWorkingDayState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorWorkingDayUpdatableRelationshipsEquals(InstructorWorkingDay expected, InstructorWorkingDay actual) {
        // empty method
    }
}
