package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LevelEducationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLevelEducationAllPropertiesEquals(LevelEducation expected, LevelEducation actual) {
        assertLevelEducationAutoGeneratedPropertiesEquals(expected, actual);
        assertLevelEducationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLevelEducationAllUpdatablePropertiesEquals(LevelEducation expected, LevelEducation actual) {
        assertLevelEducationUpdatableFieldsEquals(expected, actual);
        assertLevelEducationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLevelEducationAutoGeneratedPropertiesEquals(LevelEducation expected, LevelEducation actual) {
        assertThat(actual)
            .as("Verify LevelEducation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLevelEducationUpdatableFieldsEquals(LevelEducation expected, LevelEducation actual) {
        assertThat(actual)
            .as("Verify LevelEducation relevant properties")
            .satisfies(a -> assertThat(a.getLevelName()).as("check levelName").isEqualTo(expected.getLevelName()))
            .satisfies(a ->
                assertThat(a.getStateLevelEducation()).as("check stateLevelEducation").isEqualTo(expected.getStateLevelEducation())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLevelEducationUpdatableRelationshipsEquals(LevelEducation expected, LevelEducation actual) {
        // empty method
    }
}
