package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class LogAuditAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogAuditAllPropertiesEquals(LogAudit expected, LogAudit actual) {
        assertLogAuditAutoGeneratedPropertiesEquals(expected, actual);
        assertLogAuditAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogAuditAllUpdatablePropertiesEquals(LogAudit expected, LogAudit actual) {
        assertLogAuditUpdatableFieldsEquals(expected, actual);
        assertLogAuditUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogAuditAutoGeneratedPropertiesEquals(LogAudit expected, LogAudit actual) {
        assertThat(actual)
            .as("Verify LogAudit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogAuditUpdatableFieldsEquals(LogAudit expected, LogAudit actual) {
        assertThat(actual)
            .as("Verify LogAudit relevant properties")
            .satisfies(a -> assertThat(a.getLevelAudit()).as("check levelAudit").isEqualTo(expected.getLevelAudit()))
            .satisfies(a -> assertThat(a.getLogName()).as("check logName").isEqualTo(expected.getLogName()))
            .satisfies(a -> assertThat(a.getMessageAudit()).as("check messageAudit").isEqualTo(expected.getMessageAudit()))
            .satisfies(a ->
                assertThat(a.getDateAudit())
                    .as("check dateAudit")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateAudit())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogAuditUpdatableRelationshipsEquals(LogAudit expected, LogAudit actual) {
        assertThat(actual)
            .as("Verify LogAudit relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
