package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class LogErrorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogErrorAllPropertiesEquals(LogError expected, LogError actual) {
        assertLogErrorAutoGeneratedPropertiesEquals(expected, actual);
        assertLogErrorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogErrorAllUpdatablePropertiesEquals(LogError expected, LogError actual) {
        assertLogErrorUpdatableFieldsEquals(expected, actual);
        assertLogErrorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogErrorAutoGeneratedPropertiesEquals(LogError expected, LogError actual) {
        assertThat(actual)
            .as("Verify LogError auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogErrorUpdatableFieldsEquals(LogError expected, LogError actual) {
        assertThat(actual)
            .as("Verify LogError relevant properties")
            .satisfies(a -> assertThat(a.getLevelError()).as("check levelError").isEqualTo(expected.getLevelError()))
            .satisfies(a -> assertThat(a.getLogName()).as("check logName").isEqualTo(expected.getLogName()))
            .satisfies(a -> assertThat(a.getMessageError()).as("check messageError").isEqualTo(expected.getMessageError()))
            .satisfies(a ->
                assertThat(a.getDateError())
                    .as("check dateError")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateError())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLogErrorUpdatableRelationshipsEquals(LogError expected, LogError actual) {
        assertThat(actual)
            .as("Verify LogError relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
