package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberGroupAllPropertiesEquals(MemberGroup expected, MemberGroup actual) {
        assertMemberGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberGroupAllUpdatablePropertiesEquals(MemberGroup expected, MemberGroup actual) {
        assertMemberGroupUpdatableFieldsEquals(expected, actual);
        assertMemberGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberGroupAutoGeneratedPropertiesEquals(MemberGroup expected, MemberGroup actual) {
        assertThat(actual)
            .as("Verify MemberGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberGroupUpdatableFieldsEquals(MemberGroup expected, MemberGroup actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberGroupUpdatableRelationshipsEquals(MemberGroup expected, MemberGroup actual) {
        assertThat(actual)
            .as("Verify MemberGroup relationships")
            .satisfies(a -> assertThat(a.getProjectGroup()).as("check projectGroup").isEqualTo(expected.getProjectGroup()))
            .satisfies(a -> assertThat(a.getApprentice()).as("check apprentice").isEqualTo(expected.getApprentice()));
    }
}
