package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ObservationResponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObservationResponseAllPropertiesEquals(ObservationResponse expected, ObservationResponse actual) {
        assertObservationResponseAutoGeneratedPropertiesEquals(expected, actual);
        assertObservationResponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObservationResponseAllUpdatablePropertiesEquals(ObservationResponse expected, ObservationResponse actual) {
        assertObservationResponseUpdatableFieldsEquals(expected, actual);
        assertObservationResponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObservationResponseAutoGeneratedPropertiesEquals(ObservationResponse expected, ObservationResponse actual) {
        assertThat(actual)
            .as("Verify ObservationResponse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObservationResponseUpdatableFieldsEquals(ObservationResponse expected, ObservationResponse actual) {
        assertThat(actual)
            .as("Verify ObservationResponse relevant properties")
            .satisfies(a -> assertThat(a.getNumberObservation()).as("check numberObservation").isEqualTo(expected.getNumberObservation()))
            .satisfies(a -> assertThat(a.getObsevation()).as("check obsevation").isEqualTo(expected.getObsevation()))
            .satisfies(a -> assertThat(a.getJuries()).as("check juries").isEqualTo(expected.getJuries()))
            .satisfies(a ->
                assertThat(a.getDateObservation())
                    .as("check dateObservation")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateObservation())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObservationResponseUpdatableRelationshipsEquals(ObservationResponse expected, ObservationResponse actual) {
        assertThat(actual)
            .as("Verify ObservationResponse relationships")
            .satisfies(a -> assertThat(a.getGroupResponse()).as("check groupResponse").isEqualTo(expected.getGroupResponse()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
