package co.edu.sena.domain;

import static co.edu.sena.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PlanningAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningAllPropertiesEquals(Planning expected, Planning actual) {
        assertPlanningAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanningAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningAllUpdatablePropertiesEquals(Planning expected, Planning actual) {
        assertPlanningUpdatableFieldsEquals(expected, actual);
        assertPlanningUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningAutoGeneratedPropertiesEquals(Planning expected, Planning actual) {
        assertThat(actual)
            .as("Verify Planning auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningUpdatableFieldsEquals(Planning expected, Planning actual) {
        assertThat(actual)
            .as("Verify Planning relevant properties")
            .satisfies(a -> assertThat(a.getPlanningCode()).as("check planningCode").isEqualTo(expected.getPlanningCode()))
            .satisfies(a ->
                assertThat(a.getPlanningDate())
                    .as("check planningDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getPlanningDate())
            )
            .satisfies(a -> assertThat(a.getPlanningState()).as("check planningState").isEqualTo(expected.getPlanningState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningUpdatableRelationshipsEquals(Planning expected, Planning actual) {
        // empty method
    }
}
