package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanningActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningActivityAllPropertiesEquals(PlanningActivity expected, PlanningActivity actual) {
        assertPlanningActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanningActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningActivityAllUpdatablePropertiesEquals(PlanningActivity expected, PlanningActivity actual) {
        assertPlanningActivityUpdatableFieldsEquals(expected, actual);
        assertPlanningActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningActivityAutoGeneratedPropertiesEquals(PlanningActivity expected, PlanningActivity actual) {
        assertThat(actual)
            .as("Verify PlanningActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningActivityUpdatableFieldsEquals(PlanningActivity expected, PlanningActivity actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanningActivityUpdatableRelationshipsEquals(PlanningActivity expected, PlanningActivity actual) {
        assertThat(actual)
            .as("Verify PlanningActivity relationships")
            .satisfies(a -> assertThat(a.getQuarterSchedule()).as("check quarterSchedule").isEqualTo(expected.getQuarterSchedule()))
            .satisfies(a -> assertThat(a.getProjectActivity()).as("check projectActivity").isEqualTo(expected.getProjectActivity()));
    }
}
