package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectActivityAllPropertiesEquals(ProjectActivity expected, ProjectActivity actual) {
        assertProjectActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectActivityAllUpdatablePropertiesEquals(ProjectActivity expected, ProjectActivity actual) {
        assertProjectActivityUpdatableFieldsEquals(expected, actual);
        assertProjectActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectActivityAutoGeneratedPropertiesEquals(ProjectActivity expected, ProjectActivity actual) {
        assertThat(actual)
            .as("Verify ProjectActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectActivityUpdatableFieldsEquals(ProjectActivity expected, ProjectActivity actual) {
        assertThat(actual)
            .as("Verify ProjectActivity relevant properties")
            .satisfies(a -> assertThat(a.getActivityNumber()).as("check activityNumber").isEqualTo(expected.getActivityNumber()))
            .satisfies(a ->
                assertThat(a.getActivityDescription()).as("check activityDescription").isEqualTo(expected.getActivityDescription())
            )
            .satisfies(a ->
                assertThat(a.getProjectActivityState()).as("check projectActivityState").isEqualTo(expected.getProjectActivityState())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectActivityUpdatableRelationshipsEquals(ProjectActivity expected, ProjectActivity actual) {
        assertThat(actual)
            .as("Verify ProjectActivity relationships")
            .satisfies(a -> assertThat(a.getProjectPhase()).as("check projectPhase").isEqualTo(expected.getProjectPhase()));
    }
}
