package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectGroupAllPropertiesEquals(ProjectGroup expected, ProjectGroup actual) {
        assertProjectGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectGroupAllUpdatablePropertiesEquals(ProjectGroup expected, ProjectGroup actual) {
        assertProjectGroupUpdatableFieldsEquals(expected, actual);
        assertProjectGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectGroupAutoGeneratedPropertiesEquals(ProjectGroup expected, ProjectGroup actual) {
        assertThat(actual)
            .as("Verify ProjectGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectGroupUpdatableFieldsEquals(ProjectGroup expected, ProjectGroup actual) {
        assertThat(actual)
            .as("Verify ProjectGroup relevant properties")
            .satisfies(a -> assertThat(a.getGroupNumber()).as("check groupNumber").isEqualTo(expected.getGroupNumber()))
            .satisfies(a -> assertThat(a.getProjectName()).as("check projectName").isEqualTo(expected.getProjectName()))
            .satisfies(a -> assertThat(a.getProjectGroupState()).as("check projectGroupState").isEqualTo(expected.getProjectGroupState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectGroupUpdatableRelationshipsEquals(ProjectGroup expected, ProjectGroup actual) {
        assertThat(actual)
            .as("Verify ProjectGroup relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
