package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScheduleVersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleVersionAllPropertiesEquals(ScheduleVersion expected, ScheduleVersion actual) {
        assertScheduleVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertScheduleVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleVersionAllUpdatablePropertiesEquals(ScheduleVersion expected, ScheduleVersion actual) {
        assertScheduleVersionUpdatableFieldsEquals(expected, actual);
        assertScheduleVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleVersionAutoGeneratedPropertiesEquals(ScheduleVersion expected, ScheduleVersion actual) {
        assertThat(actual)
            .as("Verify ScheduleVersion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleVersionUpdatableFieldsEquals(ScheduleVersion expected, ScheduleVersion actual) {
        assertThat(actual)
            .as("Verify ScheduleVersion relevant properties")
            .satisfies(a -> assertThat(a.getVersionNumber()).as("check versionNumber").isEqualTo(expected.getVersionNumber()))
            .satisfies(a -> assertThat(a.getVersionState()).as("check versionState").isEqualTo(expected.getVersionState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleVersionUpdatableRelationshipsEquals(ScheduleVersion expected, ScheduleVersion actual) {
        assertThat(actual)
            .as("Verify ScheduleVersion relationships")
            .satisfies(a -> assertThat(a.getCurrentQuarter()).as("check currentQuarter").isEqualTo(expected.getCurrentQuarter()));
    }
}
