package co.edu.sena.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingStatusAllPropertiesEquals(TrainingStatus expected, TrainingStatus actual) {
        assertTrainingStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingStatusAllUpdatablePropertiesEquals(TrainingStatus expected, TrainingStatus actual) {
        assertTrainingStatusUpdatableFieldsEquals(expected, actual);
        assertTrainingStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingStatusAutoGeneratedPropertiesEquals(TrainingStatus expected, TrainingStatus actual) {
        assertThat(actual)
            .as("Verify TrainingStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingStatusUpdatableFieldsEquals(TrainingStatus expected, TrainingStatus actual) {
        assertThat(actual)
            .as("Verify TrainingStatus relevant properties")
            .satisfies(a -> assertThat(a.getStatusName()).as("check statusName").isEqualTo(expected.getStatusName()))
            .satisfies(a -> assertThat(a.getStateTraining()).as("check stateTraining").isEqualTo(expected.getStateTraining()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingStatusUpdatableRelationshipsEquals(TrainingStatus expected, TrainingStatus actual) {
        // empty method
    }
}
